analytics: {}
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 1
  lightness: 0
  rhythmicContrast: 0.528783
  saturation: 0.603618
cta: {}
layout_spectrum: 0.817434
name: JDOOGZIE
opengraph: {}
purpose: []
typography_spectrum: 0.8237652382813394
